name: Deploy to Development

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development-env
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Development
        run: echo "Deploying to ${{ vars.SERVER_URL }}"

