name: Release CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
